### ISSUE TITLE
convert2to3 fails on windows

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SBOL-utilities#122] opened 2022-04-28 12:33 UTC
tried running this simple script:

```
import sbol2
import os
import sbol_utilities.conversion as conv


doc = sbol2.Document()
comp = sbol2.Component("hello")
doc.add(comp)
cwd = os.getcwd()
file_path_out = os.path.join(cwd, "excel2sbol", 'tests', 'test_files', 'out_test.xml')
doc.write(file_path_out)

doc3 = conv.convert2to3(file_path_out)
print(doc3)
```

And had the error

```
\excel_env\lib\site-packages\rdflib_jsonld\__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from your project's dependencies.
Traceback (most recent call last):
  File "excel2sbol\temp2.py", line 13, in <module>
    doc3 = conv.convert2to3(file_path_out)
  File "\site-packages\sbol_utilities\conversion.py", **line 96, in convert2to3**
    proc = subprocess.run(cmd, capture_output=True, check=True)
  File \python\python39\lib\subprocess.py", **line 501, in run**
    with Popen(*popenargs, **kwargs) as process:
  File "python\python39\lib\subprocess.py", **line 947, in __init__**
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "python\python39\lib\subprocess.py", **line 1416, in _execute_child**
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by tcmitchell** [comment] 2022-04-28 12:42
Looking at the source code, this might be an issue for the Windows platform. It would be helpful to include in your bug report what version of sbol-utilities you are using, what version of python, and on what platform/OS you are running. (also, can you edit the comment to display the stack trace better? It's hard to read as is.)

Do you have the ability to run this script in a Unix (or macOS) environment? If you do, please try it there and report back on your results.

**Comment by JMante1** [comment] 2022-04-28 12:53
sbol-utilities     1.0a15
Python 3.9.1
Windows 10

Will try and make the trace easier to read. I don't have a unix environment. It does see like a windows issue.

**Comment by tcmitchell** [comment] 2022-04-28 12:58
I think what is happening is that the execution of [SBOLGRAPH](https://github.com/SynBioDex/SBOL-utilities/blob/develop/sbol_utilities/conversion.py#L22) relies on the [unix `#!` syntax](https://raw.githubusercontent.com/SynBioDex/SBOL-utilities/develop/sbol_utilities/sbolgraph-standalone.js) to run the `.js` file in Node.

**Comment by JMante1** [comment] 2022-04-28 13:32
All I really want is to test a simple function from the utilities library before I add to it for excel-sbol stuff. Is there another function you suggest?

**Comment by tcmitchell** [comment] 2022-04-28 13:37
> All I really want is to test a simple function from the utilities library before I add to it for excel-sbol stuff. Is there another function you suggest?

@jakebeal do you have any suggestions for @JMante1 ? My knowledge of the contents of the library are limited.

**Comment by JMante1** [comment] 2022-04-28 14:06
@tcmitchell can I just pip install sbol2to3 or do I need to git clone it from somewhere?

@tcmitchell  and change :     `cmd = [SBOLGRAPH, '-output', 'sbol3',  'import', sbol2_path, 'convert', '--target-sbol-version', '3']`

to `cmd = ['Node', SBOLGRAPH, '-output', 'sbol3',  'import', sbol2_path, 'convert', '--target-sbol-version', '3']`

**Comment by tcmitchell** [comment] 2022-04-28 14:38
`sbol2to3` is a program this is installed when you `pip install sbol-utilities`, so you should already have it accessible to you. Admittedly I don't know the particulars of how that all works on Windows, but presumably you can run it in a shell window of some sort. `sbol2to3` is not a separate install and does not require a separate git clone. See [Convert beween SBOL3 and other genetic design formats](https://github.com/SynBioDex/SBOL-utilities#convert-beween-sbol3-and-other-genetic-design-formats) in the README.

The change above looks right to me as long as `Node` is a program that you can run in your environment. Maybe it is `node`, or `node.js`. I'm not too familiar with the execution of [Node.js](https://nodejs.org/) in general, and that goes double for running it on Windows. [The getting started guide](https://nodejs.org/en/docs/guides/getting-started-guide/) indicates that it should be `node`. I assume you installed Node.js per the [README](https://github.com/SynBioDex/SBOL-utilities#readme).

**Comment by jakebeal** [comment] 2022-05-12 18:13
@JMante1 I haven't seen an update on this issue for two weeks. I am guessing that this means that you were able to resolve this issue by ensuring that Node.js was installed. If this is so, I will close the issue. If this is not the case, please speak up on this thread.

**Comment by jakebeal** [comment] 2022-05-12 21:01
We have just discovered that the "Windows" GitHub build was actually not running on Windows, but had defaulted back to ubuntu. Now that we have it actually testing on Windows, it is showing the same error message that you are getting: https://github.com/SynBioDex/SBOL-utilities/actions/runs/2315999176

Apologies for the earlier confusion --- we've got some work to do.

**Comment by udp** [comment] 2022-05-12 23:01
It definitely works on windows. I think I even included a bat file for this purpose - will check tomorrow and send the details.

**Comment by jakebeal** [comment] 2022-05-13 00:02
@udp If you have access to a Windows machine, it would be fantastic if you are able to figure out how things need to be adjusted.  I'm guessing that the problem is not your library but how we're calling it from Python --- but I don't have access to a Windows machine, which makes it challenging for me to figure out.

**Comment by udp** [comment] 2022-05-13 13:57
On https://github.com/sboltools/sboltools/releases there is a windows zip which packages the `node.exe` binary (literally just stock nodejs for windows) with an `sbol.js` file which is my code packaged up, and `sbol.cmd` which is a windows script to run something like `node.exe sbol.js`.

I don't know exactly how calling this would look from your library but I would imagine you can replace the shebang-adorned `sbol` script (which is intended for unix systems) with the above `sbol.js` on all platforms if you run it using node.

**Comment by tcmitchell** [comment] 2022-06-03 13:13
@JMante1 I have merged a fix for Windows (and macOS) to make the conversion work in the CI testing. Can you please try installing from the develop branch to see if this fix solves this issue in your environment? I don't want to close out this issue in case there is something else that is not covered by the CI testing.

Thanks!

**Comment by jakebeal** [comment] 2022-06-15 15:52
@JMante1 Since we have not heard from you, we are assuming that the fix now working here has also resolved your issue. Please reopen if that is not the case.

**Closed by jakebeal** 2022-06-15 15:52 UTC
Labels: bug
